variables:
  GIT_STRATEGY: clone
  ENV_GIT_REPO: https://gitlab-ci-token:${CI_PERSONAL_ACCESS_TOKEN}@gitlab.com/thichchocbia/defikitargocd.git
  ENV_WORKDIR: defikitargocd
  ENV_IMAGE_TAG_KEY: .image.tag

stages:
  - validate
  - init-infra
  - pre-build
  - build-image
  - deploy

.build-image:
  stage: build-image
  script:
    - export TAG=$CI_COMMIT_SHORT_SHA-$(date +%s)
    - docker build --pull -t $CI_REGISTRY_IMAGE:$TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$TAG
    - echo $TAG > image.tag
  artifacts:
    paths:
      - image.tag
  tags:
    - defikit

.deploy:
  stage: deploy
  script:
    - export TAG=$(cat image.tag)
    - git clone ${ENV_GIT_REPO} || echo "repo already exit"
    - cd ${ENV_WORKDIR}
    - pwd
    - yq e -i ''${ENV_IMAGE_TAG_KEY}' |= "'$TAG'"' ''${ENV_CFG_VALUESFILE}''
    - git add . && git commit -m "update image" && git push origin main
  tags:
    - defikit

validate:
  stage: validate
  script:
    - cd infra
    - terraform init
    - terraform validate
    - terraform plan
  only:
    refs:
      - main
      - merge_requests
    changes:
      - infra/**/*
  tags:
    - defikit

init-infra:
  stage: init-infra
  script:
    - cd infra
    - terraform init
    - terraform plan
    - terraform apply -auto-approve
  only:
    refs:
      - main
      - merge_requests
    changes:
      - infra/**/*
  tags:
    - defikit

cleanup-docker:
  stage: pre-build
  script:
    - docker system prune -a --volumes -f
  only:
    refs:
      - main
      - merge_requests
      - base
  tags:
    - defikit

build-staging:
  extends: .build-image
  only:
    refs:
      - main
      - merge_requests

build-prod:
  extends: .build-image
  only:
    refs:
      - main
      - merge_requests

deploy-staging:
  variables:
    ENV_CFG_VALUESFILE: botmatrix/stg/values.yaml
  extends: .deploy
  only:
    refs:
      - main
      - merge_requests

deploy-prod:
  variables:
    ENV_CFG_VALUESFILE: botmatrix/prod/values.yaml
  extends: .deploy
  only:
    refs:
      - main
      - merge_requests
  when: manual
