name: prepumpfunbe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t javakent91/prepump-be:${{ github.sha }} .
        docker push javakent91/prepump-be:${{ github.sha }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Update kubeconfig for EKS
      run: aws eks update-kubeconfig --region ap-southeast-1 --name defikit

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.23.0'

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: List directory
      run: ls -la

    - name: Go out
      run: cd .. && ls -la

    - name: Create Kubernetes Namespace
      run: |
        kubectl get namespace prepump-be || kubectl create namespace prepump-be

    - name: Deploy to Kubernetes using Helm
      run: |
        cd && helm upgrade --install prepumpfunbe . \
          --set image.repository=javakent91/prepump-be \
          --set image.tag=${{ github.sha }} \
          --namespace prepump-be
