name: prepump

on:
  push:
    branches:
      - main
      - master
      - 'refs/heads/merge_requests/**'
  pull_request: # For merge requests
    branches:
      - '**'

env:
  ENV_GIT_REPO: https://github.com/DefikitTeam/defikitargocdgithub
  ENV_WORKDIR: defikitargocdgithub
  ENV_IMAGE_TAG_KEY: .image.tag

jobs:
  cleanup-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up Docker
        run: docker system prune -a --volumes -f

  build-image:
    runs-on: ubuntu-latest
    needs: cleanup-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          TAG=$(echo ${{ github.ref_name }} | sed 's/\\//-/g')-${{ github.sha }}-$(date +%s)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --pull -t ${{ secrets.REGISTRY_IMAGE }}:${{ env.TAG }} .

      - name: Push Docker image
        env:
          CI_JOB_TOKEN: ${{ secrets.CI_JOB_TOKEN }}
        run: |
          echo "${{ secrets.CI_JOB_TOKEN }}" | docker login -u gitlab-ci-token --password-stdin ${{ secrets.REGISTRY_IMAGE }}
          docker push ${{ secrets.REGISTRY_IMAGE }}:${{ env.TAG }}

      - name: Save image tag
        run: echo "${{ env.TAG }}" > image.tag

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image.tag
          path: image.tag

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Download image.tag
        uses: actions/download-artifact@v3
        with:
          name: image.tag

      - name: Clone Git repository
        run: |
          git clone $ENV_GIT_REPO || echo "repo already exists"
          cd $ENV_WORKDIR

      - name: Update image tag in Helm values
        run: |
          TAG=$(cat image.tag)
          yq e -i ''"${{ env.ENV_IMAGE_TAG_KEY }}"' |= "'$TAG'"' ${{ env.ENV_CFG_VALUESFILE }}
          git add ${{ env.ENV_CFG_VALUESFILE }}
          git commit -m "Update image tag to $TAG"
          git push origin main

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      ENV_CFG_VALUESFILE: prepump/stg/be/values.yaml
    if: github.event_name == 'pull_request'

  deploy-berabear:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      ENV_CFG_VALUESFILE: prepump/stg/be/values.yaml
    if: github.ref == 'refs/heads/main'
